// All personal content lives here. Swap the placeholders for real values
// later — nothing personal is hardcoded in the components.
export const content = {
  name: "imahskaibali",
  headline: "Product Designer & Design Engineer",
  subtext: "I design and build digital products end to end.",
  email: "hello@imahskaibali.com",
  resumeUrl: "/resume.pdf",
  socials: [
    { label: "Dribbble", url: "https://dribbble.com/imahskaibali" },
    { label: "X", url: "https://x.com/imahskaibali" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/imahskaibali" },
    { label: "GitHub", url: "https://github.com/imahskaibali" },
  ],
  experience: [
    {
      company: "Vivetica AG",
      icon: "code",
      url: "https://viveticacapital.ch",
      logo: "/badges/vivetica-mark.svg",
      logoInvert: true,
      location: "Zürich, Switzerland",
      locationNote: "(Remote)",
      role: "Product Design Engineer",
      type: "Part-time",
      start: "01.2026",
      end: null, // present
      duration: "8m",
      highlights: [
        "Develop production-ready frontends and hand off to backend teams.",
        "Design and build marketing websites for company products.",
        "Design and build Pro components/blocks, from\nFigma to production-ready React.",
        "Create and maintain design systems that\nscale across multiple products.",
      ],
      tags: ["React", "TypeScript", "Next.js", "Design System", "Figma", "UX"],
    },
    {
      company: "Orbix Studio",
      icon: "pen",
      url: "https://www.orbix.studio/",
      logo: "/badges/orbix.png",
      logoInvert: false,
      location: "Mirpur, Dhaka",
      locationNote: "(On Site)",
      role: "Sr. Product Designer",
      type: "Full Time",
      start: "Jul 2025",
      end: "Aug 2025",
      duration: "1m",
      highlights: [
        "Led the design and research team to improve the studio’s portfolio.",
        "Worked on client projects and created high quality designs.",
        "Helped organize design work and guided junior designers.",
        "Left the role due to a short-term health issue.",
      ],
      tags: ["Creativity", "UI/UX Design", "Figma"],
    },
    {
      company: "ScreensDesigns",
      icon: "pen",
      url: "https://screensdesign.com",
      logo: "/badges/screens.png",
      logoInvert: false,
      location: "Tallinn, Estonia",
      locationNote: "(Remote)",
      role: "Product Designer",
      type: "Contract",
      start: "Feb 2024",
      end: "Nov 2025",
      duration: "21m",
      highlights: [
        "Designed the full Website of ScreensDesign.",
        "Worked closely with the CEO and developers to\ncreate user-friendly designs.",
      ],
      tags: ["Web Design", "UI/UX Design", "UX Research", "Figma"],
    },
    {
      company: "Hashtagfox Ou",
      icon: "pen",
      url: "https://www.inforegister.ee/en/14839166-HASHTAGFOX-OU/",
      logo: "/badges/hashtagfox.png",
      logoInvert: false,
      location: "Tallinn, Estonia",
      locationNote: "(Remote)",
      role: "Product Designer",
      type: "Contract",
      start: "Feb 2023",
      end: "Mar 2025",
      duration: "25m",
      highlights: [
        "Created a SaaS platform for machine operations, improving\nUX and driving business growth.",
        "Revamped [[Brainbubble app|https://apps.apple.com/us/app/brainbubble-ace-your-job/id1664489026]] to improve UX, boosting\nconversions and retention.",
        "Designed an AI-powered iOS photo editing app with\ninnovative user features.",
        "Designed the [[BoostVibe app|https://apps.apple.com/in/app/boostvibe-aesthetic-reels/id6451412109]], focusing on\nuser engagement and visual appeal.",
        "Added features and UX enhancements to\n[[Boost App Social|https://apps.apple.com/us/app/boost-app-social/id1551991915]], doubling revenue.",
      ],
      tags: ["App Design", "SaaS", "UX", "Figma", "HTML", "CSS"],
    },
  ],
} as const;
